### ISSUE TITLE
Updating Source causes star-sized columns to collapse

### ISSUE THREAD

**Issue by SuperJMN** [AvaloniaUI/Avalonia.Controls.TreeDataGrid#130]
I was trying to overcome [this issue](https://github.com/AvaloniaUI/Avalonia.Controls.TreeDataGrid/issues/128). To do so, I set a new Source every time the model changes, in order to force the `TreeDataGrid` to update its contents.

However, this has led me to another bug:

- When `TreeDataGrid.Source` is set the **1st time**, things go OK
- but when you try **set it afterwards, star-sized columns collapse**.

https://user-images.githubusercontent.com/3109851/190614545-0eec8fed-8cb2-4a24-b153-aa8753d23f95.mp4

The code to reproduce this is really simple. You can reproduce it by cloning [this repo](https://github.com/SuperJMN-Tutorials/TreeDataGrid-WeirdColumnBehavior)

TreeDataGrid version: 0.10.10

**Comment by FrayxRulez** [comment]
This should be relatively easy to address, as a workaround we're doing this right after setting the `Source`:
```csharp
void layoutUpdated(object? sender, EventArgs e)
{
    Tree.LayoutUpdated -= layoutUpdated;

    var c = Tree.RowsPresenter?.GetVisualParent();
    if (c != null)
    {
        Tree.RowsPresenter?.Columns?.ViewportChanged(new Rect(0, 0, c.Bounds.Width, c.Bounds.Height));
    }
}

Tree.LayoutUpdated += layoutUpdated;
```
