### ISSUE TITLE
Text cell edit mode doesn't update model

### ISSUE THREAD

**Issue by jp2masa** [AvaloniaUI/Avalonia.Controls.TreeDataGrid#139]
## Bug

Changing a value in a text cell doesn't call the setter.

## Proposed fixes

I think `DataContext` should be replaced with `Model` in the following lines:

https://github.com/AvaloniaUI/Avalonia.Controls.TreeDataGrid/blob/babd474c9391e9faa55545c223e366d0fd2f130f/src/Avalonia.Controls.TreeDataGrid/Primitives/TreeDataGridCell.cs#L64

https://github.com/AvaloniaUI/Avalonia.Controls.TreeDataGrid/blob/babd474c9391e9faa55545c223e366d0fd2f130f/src/Avalonia.Controls.TreeDataGrid/Primitives/TreeDataGridCell.cs#L72

https://github.com/AvaloniaUI/Avalonia.Controls.TreeDataGrid/blob/babd474c9391e9faa55545c223e366d0fd2f130f/src/Avalonia.Controls.TreeDataGrid/Primitives/TreeDataGridCell.cs#L78

However, this is not enough, as `TextCell.Value` is never updated, so `EndEdit` always fails. I think that some kind of binding has to be set up on realize, i.e. here:

https://github.com/AvaloniaUI/Avalonia.Controls.TreeDataGrid/blob/babd474c9391e9faa55545c223e366d0fd2f130f/src/Avalonia.Controls.TreeDataGrid/Primitives/TreeDataGridTextCell.cs#L40-L46

Could someone with more experience in this codebase please help me fixing this?

**Comment by guilhermeolisi** [comment]
Hi, I have the same issue here

**Comment by grokys** [comment]
Fixed by #162
