### ISSUE TITLE
Exception  , TreeDataGridDemo , Drag/Drop use case

### ISSUE THREAD

**Issue by elix22** [AvaloniaUI/Avalonia.Controls.TreeDataGrid#143]
https://user-images.githubusercontent.com/7060531/201541149-fe9a5ecd-c0a1-40e7-992b-959b427e0e22.mp4

The video is self-explanatory , 100% reproducible
1- Expand destination
2-Collapse destination
3 -Drag to destination

**Comment by anakrivokuca** [comment]
I am also experiencing the same exception when updating the item view model property value after doing Expand/Collapse: System.ArgumentOutOfRangeException: 'Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')'
