### ISSUE TITLE
TreeDataGrid - Latest version throws exception when application starts

### ISSUE THREAD

**Issue by kurtyoder** [AvaloniaUI/Avalonia.Controls.TreeDataGrid#156]
I'm struggling to get the tree data grid to work in Avalonia 11-preview6. Version 11-preview1 of the table was working in Avalonia 11-preview4, but updating everything to the latest version has broken the control.

**App.axaml**

```
   <Application.Styles>
        <FluentTheme/>
        <StyleInclude Source="avares://Avalonia.Controls.TreeDataGrid/Themes/Fluent.axaml"/>
    </Application.Styles>
```

**Dependencies**

```
<ItemGroup>
        <PackageReference Include="Avalonia" Version="11.0.0-preview6" />
        <PackageReference Include="Avalonia.Controls.TreeDataGrid" Version="11.0.0-preview4" />
        <PackageReference Include="Avalonia.Desktop" Version="11.0.0-preview6" />
        <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="11.0.0-preview6" />
        <PackageReference Include="Avalonia.ReactiveUI" Version="11.0.0-preview6" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.0.0-preview6" />
    </ItemGroup>
```

**Exception**

> System.MethodAccessException: Attempt by method '[PROJECTNAME].App.!XamlIlPopulate(System.IServiceProvider, [PROJECTNAME].App)' to access method 'CompiledAvaloniaXaml.!AvaloniaResources.Build:/Themes/Fluent.axaml(System.IServiceProvider)' failed.
>    at [PROJECTNAME].App.!XamlIlPopulate(IServiceProvider, App) in [PROJECTPATH]\App.axaml:line 27
>    at [PROJECTNAME].App.!XamlIlPopulateTrampoline(App)
>    at[PROJECTNAME].App.Initialize() in [PROJECTPATH]\App.axaml.cs:line 20
>    at Avalonia.AppBuilder.Setup() in /_/src/Avalonia.Controls/AppBuilder.cs:line 263
>    at Avalonia.AppBuilder.SetupWithLifetime(IApplicationLifetime lifetime) in /_/src/Avalonia.Controls/AppBuilder.cs:line 162
>    at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 213
>    at [PROJECTNAME].Program.Main(String[] args) in [PROJECTPATH]\Program.cs:line 28

**Comment by Numpsy** [comment]
Theres a pull request open at https://github.com/AvaloniaUI/Avalonia.Controls.TreeDataGrid/pull/153 to get it working with Avalonia 11 preview 6
