### ISSUE TITLE
The last row of data is blocked by the scroll bar

### ISSUE THREAD

**Issue by bouyeijiang** [AvaloniaUI/Avalonia.Controls.TreeDataGrid#169]
![image](https://user-images.githubusercontent.com/4083760/233876693-1bf7bf6d-cf1e-48ce-8140-6d7de84893db.png)

**Comment by maxkatz6** [comment]
ScrollViewer has AllowAutoHide property. By default, it is enabled, and scroll bar is shown on top of the scrolling content, when you hover over it. And normally scroll bar is "hidden" into the small line.
When AllowAutoHide is disabled, it's always visible in full size and also is not displayed on top of the content (i.e. makes less space for it). 

Alternatively, you can keep AllowAutoHide enabled, but add small Padding on the bottom to the grid/scrollviewer.
