### ISSUE TITLE
Scroll is not updated sometimes when setting items source

### ISSUE THREAD

**Issue by danipen** [AvaloniaUI/Avalonia.Controls.TreeDataGrid#174]
Simple repro case: https://github.com/danipen/TreeDataGridScrollIssue

The example basically sets lists of different sizes in the `TreeDataGrid`, based on the `TextBox.Text.Length`. So when you type chars in the `TextBox` the list source is updated with new items.

https://user-images.githubusercontent.com/501613/235617213-05386350-a854-4600-9ea9-948c75e2a493.mp4

So when text is typed in the `TextBox `for the first time, the `TreeDataGrid `scroll is updated, but once you start deleting characters, the scroll is not updated anymore.

**Comment by grokys** [comment]
Should be fixed by https://github.com/AvaloniaUI/Avalonia/pull/11233
