### ISSUE TITLE
Arbitrary selection of elements at Selection

### ISSUE THREAD

**Issue by ILD3225** [AvaloniaUI/Avalonia.Controls.TreeDataGrid#184]
Arbitrary selection of elements at Selection

Sometimes this effect occurs after scrolling, opening and closing nodes.

11.0.0-preview8

https://github.com/AvaloniaUI/Avalonia.Controls.TreeDataGrid/assets/14194323/b6adcfca-7675-4043-a47c-d4c1193c72ab

**Comment by grokys** [comment]
Could be: I've done a quick port of those changes here: #241 but I've not had time to write tests or even manually test it. If you'd be able to try it to see if it fixes your issues, that would be appreciated.

**Comment by ILD3225** [comment]
> Could be: I've done a quick port of those changes here: #241 but I've not had time to write tests or even manually test it. If you'd be able to try it to see if it fixes your issues, that would be appreciated.

Hello @grokys 
I tested your branch and couldn't reproduce the previously incorrect behavior.
You can close the task.
Thank you =)

**Comment by xLEGiON** [comment]
I've also just tested the pull request and it fixed the issue for me too. Thank you!
