### ISSUE TITLE
Columns with Star width are set to the minimum available width

### ISSUE THREAD

**Issue by berruezo** [AvaloniaUI/Avalonia.Controls.TreeDataGrid#209]
When setting a `GridLength` of `GridUnitType.Star` in a `TemplateColumn`, the actual width is not calculated correctly, and the column gets the minimum width possible:

![image](https://github.com/AvaloniaUI/Avalonia.Controls.TreeDataGrid/assets/28261333/b02e2b65-6658-4cb6-8769-633a7036a3a7)

Digging into the code I saw that this method is always receiving 0 as the `availableWidth`, whereas in the previous version it received the actual available width for the column
![image](https://github.com/AvaloniaUI/Avalonia.Controls.TreeDataGrid/assets/28261333/fb9e5781-a584-47d4-94ef-6246d22b9896)

**Comment by grokys** [comment]
I've tried to repro this but been unable to. I know we spoke in chat and you were unable to get a simple repro, but could you maybe describe how your columns are set up? Might give more of a clue.

**Comment by berruezo** [comment]
Yes, the `TemplateColumns` in the table are created using this method:
```c#
        static IColumn<T> BuildTemplateColumn(
            string columnName,
            int columnWidth,
            Func<string, T, PlasticTableCell> cellFunc,
            IComparer<T> comparer)
        {
            return new TemplateColumn<T>(
                columnName,
                new FuncDataTemplate<T>((T node, INameScope ns) =>
                {
                    return BuildCellControl(columnName, cellFunc, node);
                }, true),
                null,
                GetGridLength(columnWidth),
                new TemplateColumnOptions<T>
                {
                    CompareAscending = Sort(comparer, false),
                    CompareDescending = Sort(comparer, true)
                })
            {
                Tag = columnName,
            };
``` 

For the first column, the grid length is `new GridLength(1, GridUnitType.Star);`
And for the other two it's `new GridLength(100, GridUnitType.Pixel);`

Also, the `TreeDataGrid` is inside a non-resizable Window; it has a fixed width, and these two options:
```c#
            CanResize = false;
            SizeToContent = SizeToContent.Height;
```

**Comment by berruezo** [comment]
I saw that when executing a `LayoutPass` on the `TreeDataGrid` the `Bounds.Size` is `0,0`.

![image](https://github.com/AvaloniaUI/Avalonia.Controls.TreeDataGrid/assets/28261333/96acae85-3698-451f-9e94-1bf1e3292dd3)

The `EffectiveViewport.Size` is correct, but the `Intersect` operation is causing the `Viewport` to be of size `0,0` as well, and thus using a wrong `availableWidth` when calculating the star width. 

![image](https://github.com/AvaloniaUI/Avalonia.Controls.TreeDataGrid/assets/28261333/f9001e05-d6bd-4380-b176-f001030e83ea)

On the previous version, the `Bounds.Size` was correct, and the `Viewport` was not empty when exiting this method.
Is this of any help?

**Comment by grokys** [comment]
Ok, the missing part was that the `TreeDataGrid` needs to have no items for this to repro. Fix incoming.
