### ISSUE TITLE
Cannot expand nodes with the keyboard after collapsing them

### ISSUE THREAD

**Issue by danipen** [AvaloniaUI/Avalonia.Controls.TreeDataGrid#211]
The following sequence of actions reproduces the case.

- Open the demo app (section files).
- Select a child node.
- Press <kbd>Left</kbd> arrow key (root is selected)
- Press <kbd>Left</kbd> arrow key (root is collapsed)
- Press <kbd>Right</kbd> arrow key **(root should be expanded and it's not)**

Check the following video for a complete repro:

https://github.com/AvaloniaUI/Avalonia.Controls.TreeDataGrid/assets/501613/f62b0d7a-83c4-4968-8318-50f18a4c2390

**Comment by grokys** [comment]
The problem is that when moving selection via the keyboard, the focus isn't updated, so when the root row is collapsed, the child row still has focus. Collapsing causes it to be removed from the tree causing focus to be set to `null`.
