### ISSUE TITLE
Selecting too many nodes blocks the UI thread

### ISSUE THREAD

**Issue by danipen** [AvaloniaUI/Avalonia.Controls.TreeDataGrid#222]
In the demo app, if you select a large number of nodes (around 15k), it makes the app slow and unresponsive. This happens because the selection process takes a long time and it's happening on the main UI thread. 

Steps to reproduce:

- Create a directory on disk with 15k files.
- Open the demo app, and go to the "Files" tab.
- Expand the directory with 15k.
- Scroll to the top.
- Select the root node.
- Scroll to the bottom.
- Press <kbd>Shift</kbd> and click the last node, to cause the `TreeDataGrid `to select all the nodes.
- The application becomes unresponsive.

You can see the problem in this video:

https://github.com/AvaloniaUI/Avalonia.Controls.TreeDataGrid/assets/501613/6795679f-27c8-42e5-b816-89b9dc69ec1b

**Comment by grokys** [comment]
Just tried, and indeed it was slow, so I hit pause and noticed that it's logging a load of messages to the debug window. If I comment out these lines, it's instantaneous on my machine:

https://github.com/AvaloniaUI/Avalonia.Controls.TreeDataGrid/blob/master/samples/TreeDataGridDemo/ViewModels/FilesPageViewModel.cs#L215-L218

Could you try that on your machine?

**Comment by danipen** [comment]
Yes, the slowdown was caused by the log. We can close this issue.
