### ISSUE TITLE
Unsaported Project NET version

### ISSUE THREAD

**Issue by KrzysztofDusko** [AvaloniaUI/Avalonia.Controls.TreeDataGrid#232]
Hello,
TreeDataGrid is using NET5 which is end of life at this time
https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core

https://github.com/AvaloniaUI/Avalonia.Controls.TreeDataGrid/blob/ad009669e0ffea7e24db0cab52881229adc093d6/src/Avalonia.Controls.TreeDataGrid/Avalonia.Controls.TreeDataGrid.csproj#L3

Can we update this at least to NET 6 or wait a moment and use NET 8?

**Comment by grokys** [comment]
The reason TDG is still on .net 5 is that one of our customers is stuck on that version due to hardware limitations. We should consider targeting netstandard2 and .net6 as in the main repository but this will be a little more work as we use features that aren't available in netstandard2 here.

**Comment by KrzysztofDusko** [comment]
thanks for reponse
