### ISSUE TITLE
How to focus on cell?

### ISSUE THREAD

**Issue by artizzq** [AvaloniaUI/Avalonia.Controls.TreeDataGrid#248]
I know that I can select cell by defining CellIndex and after that put it to SelectedIndex variable. Then I find the cell manually and see that its really selected.

So how do I scroll into the selected cell automatically?

Tried TryGetCell method (I got Null exception), messing around with scrollbars of the TreeDataGrid (Misplaced and messed up header and rows) but no luck.

**Comment by maxkatz6** [comment]
You might need to call `BringIntoView(rowIndex)` first to get row materialized. And then focus.

If row/cell is outside of the viewport, its container won't exist, so there would be nothing to focus.

**Comment by artizzq** [comment]
Big thanks for help! 😌
