### ISSUE TITLE
[Question] Is TreeDataGrid more performant than TreeView

### ISSUE THREAD

**Issue by ClassyCircuit** [AvaloniaUI/Avalonia.Controls.TreeDataGrid#252]
Are there any performance improvements comparing TreeDataGrid to TreeView, when it comes down to huge hierarchical trees (without extra columns). 
I know that TreeView does not work well with large amount of data, is it the same with TreeDataGrid, or have you fixed that issue by design?

**Comment by maxkatz6** [comment]
Yes. TreeView is poorly virtualized, and it introduces nesting for each tree level. When TreeDataGrid is structured "flat" in the visual tree of elements, just applying the offset.
So, yes, you can expect TreeDataGrid to be more performant on huge data sets. Especially on deep ones.
