### ISSUE TITLE
Downloading fresh zip of Avalonia.Controls.TreeDataGrid current as of 2024-02-20, compile has build errors in the test components.

### ISSUE THREAD

**Issue by KentSwan** [AvaloniaUI/Avalonia.Controls.TreeDataGrid#261]
Environment Microsoft Visual Studio Community 2022 (64-bit) - Current Version 17.9.0
Windows 10 Pro (up to date)
Core I7 with 16 G Memory
New development using Avalonia 11.0.9 

Downloaded Avalonia.Controls.TreeDataGrid-master.zip on 2024-01-26
Unzipped 
Started VS2022
Selected the .sln file from above
Selected the TreeDataGridDemo as the Startup Program
Compiled and got a following package error in the Test subproject

Severity	Code	Description	Project	File	Line	Suppression State
Error	NETSDK1004	Assets file 'C:\Users\hkswa\Documents\projects\Projects - WBE Avalonia Playground\Avalonia.Controls.TreeDataGrid-master 2024-02-20\Avalonia.Controls.TreeDataGrid-master\tests\Avalonia.Controls.TreeDataGrid.Tests\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	Avalonia.Controls.TreeDataGrid.Tests	C:\Program Files\dotnet\sdk\7.0.313\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets	266

**Comment by maxkatz6** [comment]
It doesn't seem to be any issue with the code. 
Exact error is clear enough for me: `obj\project.assets.json' not found. Run a NuGet package restore to generate this file. `.
For some reason NuGet restore cannot be completed. There could be more errors to it, or your dev environment needs to be repaired.

**Comment by KentSwan** [comment]
Thanks for your feedback. I'm taking another more conventional approach to recasting the TreeDataGridDemo into two properly organized MVVM format sample apps with identical independent views.  These will use the Nuget load of the TreeDataGrid package. The first version will keep Reactive UI and the follow-up version will convert it to CommunityToolkit.Mvvm.   I'll put them up here to let you all have a look-see.
