### ISSUE TITLE
How can you sort a TreeDataGrid by column programatically?

### ISSUE THREAD

**Issue by Sewer56** [AvaloniaUI/Avalonia.Controls.TreeDataGrid#268]
```csharp
// Set the source
var source = CreateTreeSource(ViewModel!.Items); // Returns HierarchicalTreeDataGridSource

// Sort by first column
source.SortBy(source.Columns[0], ListSortDirection.Ascending);

// Assign the source
treeDataGrid.Source = source;
```

This took a bit longer to figure out than I expected, so figured I'd leave a Q & A.
Just leaving this in case someone else gets stuck looking for a solution, you're welcome.

**Comment by djeikyb** [comment]
I tried this with the FlatTreeDataGridSource and got a compiler error:

> Cannot access explicit implementation of 'ITreeDataGridSource. SortBy'

Which I solved by casting to the interface, and _then_ calling SortBy!

```csharp
var asInterface = ((ITreeDataGridSource) source);
asInterface.SortBy(source.Columns[1], ListSortDirection.Descending);
```
