### ISSUE TITLE
[Feature] Allow remove `Columns` from `Source`

### ISSUE THREAD

**Issue by Tulesha** [AvaloniaUI/Avalonia.Controls.TreeDataGrid#285]
Hello, I have a `TreeDataGrid` in my project and I would like to remove `Columns` from it.

As I understand this feature is not available yet. For example, trying to remove `Column` from `HierarchicalTreeDataGridSource` throws [exception](https://github.com/AvaloniaUI/Avalonia.Controls.TreeDataGrid/blob/56ac8970ad08a50ab19097e458be7188b95d8e05/src/Avalonia.Controls.TreeDataGrid/HierarchicalTreeDataGridSource.cs#L362).

Will this feature be implemented in the near future?

**Comment by heuristicAL** [comment]
Does #148 work for your use-case? I don't know when it will be merged and deployed, though.

**Comment by danwalmsley** [comment]
fixed by

https://github.com/AvaloniaUI/Avalonia.Controls.TreeDataGrid/pull/310

https://github.com/AvaloniaUI/Avalonia.Controls.TreeDataGrid/pull/311
