### ISSUE TITLE
Consider making `TreeDataGrid` more extensible.

### ISSUE THREAD

**Issue by heuristicAL** [AvaloniaUI/Avalonia.Controls.TreeDataGrid#286]
A couple of changes that could be made to `TreeDataGrid`:
- Change the `private` fields to `protected`
- Change some of the methods to be `virtual`

This could be very useful for people who try to make controls that extend TreeDataGrid that would require enough changes to the control that it doesn't make sense to inline them into the main project (or it doesn't align with the vidion of the base `TreeDataGrid`), but maintaining a full fork is too much.

**Comment by maxkatz6** [comment]
There needs to be a good reason to change modifiers to be more public/protected, as it makes maintenance of the project much and much harder. 

Consider opening issues for specific features and specific extensibility points you might need in your project.

**Comment by heuristicAL** [comment]
FWIW: I was considering making treedatagrid work with `DynamicData` `IChangeSet`s, which would entail a decent amount of changes to how the sorting works and would allow a relatively extensible way to provide column-based filtering too. Without the sort methods being overrideable on the datasources (and others on the `TreeDataGrid` class), it's looking like there will be a lot of duplicated code just to override the way those methods operate for this use-case.
