### ISSUE TITLE
[Question] New Release?

### ISSUE THREAD

**Issue by neondev9** [AvaloniaUI/Avalonia.Controls.TreeDataGrid#287]
Hi,
I'm looking for a way to support CollapseAll/ExpandAll functionality.

Just found these commits, which added that into HierarchicalTreeDataGridSource:
https://github.com/AvaloniaUI/Avalonia.Controls.TreeDataGrid/commit/bbfa905bba336c26fc0ce8d6848d438d105dc717
https://github.com/AvaloniaUI/Avalonia.Controls.TreeDataGrid/commit/d73b29439b08aa311e0549d577b1d503066023e2
Not included in latest available version (11.0.2) yet.

Do you have a plan to release new version to include these changes?

Regards,
Kostiantyn

**Comment by maxkatz6** [comment]
Just pushed a new release. Thanks!

**Comment by neondev9** [comment]
Thanks a lot.
