### ISSUE TITLE
TreeDataGrid gets stuck when a row with multiline text is added

### ISSUE THREAD

**Issue by kaminova** [AvaloniaUI/Avalonia.Controls.TreeDataGrid#43]
When a row with multiline text is added, the scroll starts to slow down. Also seems like some mess happens with virtualization

![TreeDataGrid-multiline](https://user-images.githubusercontent.com/45092470/136925403-0dee6c7c-6d86-4dcd-a8c3-f0827349ff1d.gif)

**Comment by grokys** [comment]
Should be fixed by #136
